=== jasmhusc/javaweb/xml/src/com/hsc/dtd/books.dtd
<!ELEMENT bookshelf (book)+ >
<!ELEMENT book (name,author,date)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST book id ID #REQUIRED>
<!ATTLIST book vip CDATA #IMPLIED>

=== jasmhusc/javaweb/xml/src/com/hsc/xml/books.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE bookshelf SYSTEM  "../dtd/books.dtd">
<bookshelf>
    <book id="U1001" vip="true">
        <name>西游记</name>
        <author>吴承恩</author>
        <date>1953</date>
    </book>
    <book id="U1002">
        <name>三国演义</name>
        <author>罗贯中</author>
        <date>1920</date>
    </book>

</bookshelf>
