=== jasmhusc/javaweb/xml/src/com/hsc/dtd/stus.dtd
<!ELEMENT stus (stu)+>
<!ELEMENT stu (name,age,sex)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ATTLIST stu id ID #REQUIRED>

=== jasmhusc/javaweb/xml/src/com/hsc/xml/stus.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE stus SYSTEM "../dtd/stus.dtd">
<stus>
    <stu id="U1001">
        <name>李白</name>
        <age>26</age>
        <sex>男</sex>
    </stu>
    <stu id="U1002">
        <name>杜甫</name>
        <age>24</age>
        <sex>男</sex>
    </stu>

</stus>
