=== jasmhusc/javaweb/xml/src/com/hsc/xsd/contact.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.hsc.com/contact"
        elementFormDefault="qualified">

        <element name="contactList">
            <complexType>
                <sequence>
                    <element name="contact" maxOccurs="unbounded">
                        <complexType>
                            <sequence>
                                <element name="name" type="string"></element>
                                <element name="gender">
                                    <simpleType>
                                        <restriction>
                                            <enumeration value="male"/>
                                            <enumeration value="female"/>
                                        </restriction>
                                    </simpleType>
                                </element>
                                <element name="email">
                                    <simpleType>
                                        <restriction>
                                            <pattern value="([A-z0-9_\-\.])+\@([A-z0-9_\-\.])+\.([A-z]{2,4})"/>
                                        </restriction>
                                    </simpleType>
                                </element>
                            </sequence>
                            <attribute name="id" type="int" use="required"/>
                            <attribute name="vip" type="boolean" use="optional"/>
                        </complexType>
                    </element>
                </sequence>
            </complexType>
        </element>
</schema>

=== jasmhusc/javaweb/xml/src/com/hsc/xml/contact.xml
<?xml version="1.0" encoding="UTF-8" ?>
<contactList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.hsc.com/contact"
         xsi:schemaLocation="http://www.hsc.com/contact ../xsd/contact.xsd">

    <contact id="101" vip="true">
        <name>潘金莲</name>
        <gender>female</gender>
        <email>panpan@shuihu.com</email>
    </contact>
    <contact id="102" vip="true">
        <name>武松</name>
        <gender>male</gender>
        <email>wusong@shuihu.com</email>
    </contact>
    <contact id="103">
        <name>武大郎</name>
        <gender>male</gender>
        <email>wuda@shuihu.com</email>
    </contact>

</contactList>
