=== jasmhusc/javaweb/xml/src/com/hsc/xsd/stus.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.hsc.org/stus"
elementFormDefault="qualified">

    <element name="stus">
        <complexType>
            <sequence maxOccurs="unbounded">
                <element name="stu">
                    <complexType>
                        <sequence>
                            <!--基本元素，给一下type类型，或者给一下限定条件-->
                            <element name="name" type="string"></element>
                            <element name="age">
                                <simpleType>
                                    <restriction base="integer">
                                        <minInclusive value="0"></minInclusive>
                                        <maxInclusive value="120"></maxInclusive>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="gender">
                                <simpleType>
                                    <restriction>
                                        <!--<pattern value="男|女"></pattern>-->
                                        <enumeration value="男"/>
                                        <enumeration value="女"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="address" type="all"></element>
                            <any minOccurs="0"/>
                        </sequence>
                        <!--属性标签attribute 必须给定：required-->
                        <attribute name="id" type="string" use="required"/>
                        <!--<anyAttribute> 元素使我们有能力通过未被 schema 规定的属性来扩展 XML 文档！
                            所使用的属性需要在其他 schema 内声明-->
                        <anyAttribute/>
                    </complexType>
                </element>
                <!--<any> 元素使我们有能力通过未被 schema 规定的元素来拓展 XML 文档！
                    所使用的元素需要在其他 schema 内声明-->
                <any minOccurs="0"/>
            </sequence>
        </complexType>
    </element>


</schema>

=== jasmhusc/javaweb/xml/src/com/hsc/xsd/stus2.xml
<?xml version="1.0" encoding="UTF-8"?>
<stus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.hsc.org/stus"
      xmlns:xs="http://www.microsoft.com/monitor"
      xmlns:aa="http://www.microsoft.com/attribute"
      xsi:schemaLocation="http://www.hsc.org/stus stus.xsd
    http://www.microsoft.com/monitor monitor.xsd
    http://www.microsoft.com/attribute attribute.xsd">
    <stu id="10086">
        <name>吴彦祖</name>
        <age>30</age>
        <gender>男</gender>
        <address>香港</address>
    </stu>
    <!--扩展属性：class-->
    <stu id="10087" aa:class="8">
        <name>胡歌</name>
        <age>31</age>
        <gender>男</gender>
        <address>台湾</address>
    </stu>
    <stu id="10098">
        <name>范冰冰</name>
        <age>29</age>
        <gender>女</gender>
        <address>中国</address>
        <!--<star></star> 此元素没有声明，命名空间也没有引入相关约束-->
        <xs:monitor>
            <xs:nickname>范爷</xs:nickname>
            <xs:gender>female</xs:gender>
        </xs:monitor>
    </stu>
    <!--扩展标签-->
    <xs:monitor>
        <xs:nickname>StephenChow</xs:nickname>
        <xs:gender>male</xs:gender>
    </xs:monitor>
</stus>
